"use clint";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from './_Components/toastProvider';
import CompleteProfileWrapper from "./_Components/completeProfilewrapper";
import { SessionProvider } from "next-auth/react";
import { auth } from "./_lib/auth";
import NextTopLoader from 'nextjs-toploader';
import { GlobalContextProvider } from "./_Components/Context/globalContext";
// import {} from "./_Components/Context/globalContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Enchance blogging",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session=await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
            <NextTopLoader showSpinner={true}/>
            <SessionProvider session={session}>
            <CompleteProfileWrapper>
              <ToastProvider>
                {children}
              </ToastProvider>
              </CompleteProfileWrapper>
            </SessionProvider>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
